AddonId: Stardust 2.0_1fb333b2-255b-43dd-aec1-8e2f2d5ea002
Packages:
  - Version: 2.0
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-09-07
    PackageUrl: https://github.com/darklinkpower/Stardust/releases/download/2.0-beta.1/Stardust_2.0_1fb333b2-255b-43dd-aec1-8e2f2d5ea002_2_0.pthm
    Changelog:
      - Playnite 9 support
      - DuplicateHider Extension support
  - Version: 2.1
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-09-09
    PackageUrl: https://github.com/darklinkpower/Stardust/releases/download/2.1/Stardust_2.0_1fb333b2-255b-43dd-aec1-8e2f2d5ea002_2_1.pthm
    Changelog:
      - Details View - Add SuccessStory, SystemChecker and CheckLocalizations plugins support
      - Details View - Add SuccessStory achievements summary
      - Details View - Fix Completion status button style
      - Details View - Fix notes tab showing when game doesn't have notes
      - Details View - Fix certain plugin elements showing when games don't have data
      - Grid View - Add SuccessStory support
      - Grid View - Fix item border not having corner radius
      - Grid View - Fix certain plugin elements showing when games don't have data
      - Top panel - Fix plugins buttons position setting not affecting their position
      - Top panel - Moved notification icon position
      - Explorer Panel - Change template of items in list
      - Misc fixes and improvements
  - Version: 2.2
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-09-18
    PackageUrl: https://github.com/darklinkpower/Stardust/releases/download/2.2/Stardust_2.0_1fb333b2-255b-43dd-aec1-8e2f2d5ea002_2_2.pthm
    Changelog:
      - 'Details View: Fix plugin butttons using all available width'
      - 'Details View: Add logo and video support using Extra Metadata Loader extension'
      - 'Grid View: Add logo support using Extra Metadata Loader extension'
  - Version: 2.3
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/Stardust/releases/download/2.3/Stardust_2.0_1fb333b2-255b-43dd-aec1-8e2f2d5ea002_2_3.pthm
    Changelog:
      - 'Update to changes in Playnite 9 stable release'
      - 'Top Panel: View button show toggle state'
      - 'Details View: Add Review Viewer extension support'
      - 'Details View: Fix all text inside tabs having bold font weight'
      - 'Grid View: Add Review Viewer extension support'
      - 'List View: Group count styling'
  - Version: 2.4
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-10-06
    PackageUrl: https://github.com/darklinkpower/Stardust/releases/download/2.4/Stardust_2.0_1fb333b2-255b-43dd-aec1-8e2f2d5ea002_2_4.pthm
    Changelog:
      - 'Grid View: Increase opacity of Duplicated Hider extension icons'
      - 'Explorer Panel: Remove custom control template'
      - 'Top Panel: Use hand cursor for notification button and messages'
      - 'Minor fixes and improvements'
  - Version: 2.5
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/Stardust/releases/download/2.5/Stardust_2.0_1fb333b2-255b-43dd-aec1-8e2f2d5ea002_2_5.pthm
    Changelog:
      - 'DetailsView: Fix text in horizontal details being cut when font is too large'
      - 'Details View: Add ThemeModifier variable to configure if Extra Metadata Loader logos can be used in the view'
      - 'Grid View: Add ThemeModifier variable to configure if Extra Metadata Loader logos can be used in the view'